---
title: "Quarto Practice"
format: html
editor: visual
execute: 
  warning: false 
---

Suppression warning and messages JUST for this code chunk

```{r}
#| warning: false
#| message: false 
library(tidyverse)
```

Running code but not showing code or output

```{r}
#| include: false
#return the first 6 lines of the starwars data 
head(starwars)

#return the dimensions of the starwars data 
dim(starwars)
```

Showing output but no code

```{r}
#| warning: false
#| echo: false

ggplot(data = starwars, aes(x = height, y = mass, color = mass)) +
  geom_point() +
  labs(x = "Height (cm)", 
       y = "Mass (kg)")
```

star```{r}
#| warning: false
#| fig-cap: "caption text"
#| fig-alt: "figure alt text"
ggplot(data = starwars, aes(x = height)) +
  geom_histogram(color = "blue", fill = "pink")
```

Find summary stats for Star Wars characters

```{r}
sw_height_mean <- mean(starwars$height, na.rm = TRUE)
sw_height_median <- median(starwars$height, na.rm = TRUE)
sw_height_var <- var(starwars$height, na.rm = TRUE)
sw_height_sd <- sd(starwars$height, na.rm = TRUE)
```

The mean height of the characters in Star Wars is `r round(sw_height_mean)` centimeters.
